name: h4pay
description: A new Flutter project.
publish_to: "none"
version: 2.0.6+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  http:
  custom_navigation_bar:
  cached_network_image:
  transparent_image:
  flutter_dotenv:
  shared_preferences:
  shimmer: ^2.0.0
  webview_flutter: ^2.0.14
  cupertino_icons: ^1.0.2
  url_launcher:
  animated_check: ^1.0.0
  intl: ^0.17.0
  barcode_widget: ^2.0.1
  crypto: ^3.0.1
  localstorage:
  new_version: ^0.2.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.22.0
  blur: ^3.0.0
  connectivity: ^3.0.6
  file_picker: ^4.1.1
  package_info: ^2.0.2
  screen_brightness: ^0.0.4
  wakelock: ^0.5.6
  flutter_svg_provider: ^0.1.10
  uni_links: ^0.5.1
  flutter_launcher_icons:
  in_app_update: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - assets/svg/support.svg
    - assets/image/H4pay.png
    - assets/image/pattern.png

  fonts:
    - family: Spoqa_Han_Sans
      fonts:
        - asset: assets/font/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: assets/font/SpoqaHanSansNeo-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/appIcon.png"