// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8dLNvYOV36hb1O4giqi264rjlFKKyJ0',
    appId: '1:420160555392:android:bd2448626cbd2db5249965',
    messagingSenderId: '420160555392',
    projectId: 'h4pay-0921',
    storageBucket: 'h4pay-0921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOl2KUD1sxfR9aQxEGWSOPGKO_8OLmLgk',
    appId: '1:420160555392:ios:9c3f5df8b193280e249965',
    messagingSenderId: '420160555392',
    projectId: 'h4pay-0921',
    storageBucket: 'h4pay-0921.appspot.com',
    androidClientId:
        '420160555392-pffnprdk524i4u3l5943si7g6k84j2sd.apps.googleusercontent.com',
    iosClientId:
        '420160555392-h3ka9p6vo7qu93pslabjqpagb88ttjv6.apps.googleusercontent.com',
    iosBundleId: 'com.cozyllc.h4pay',
  );
}
